name             'shell_to_chef'
maintainer       'NastyGal04'
maintainer_email 'zishan.malik@shopnastygal.com'
license          'All rights reserved'
description      'Installs/Configures shell_to_chef'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'apache2'
depends 'mysql'
depends 'php'
